### ISSUE TITLE
if we use more than 6 times its blocking as too many request implement proxy or sock5

### ISSUE THREAD

**Issue by balook** [soyreda/dorksy#1]
# if we use more than 6 times its blocking as too many request implement proxy or sock5

**Comment by balook** [comment]
```
Traceback (most recent call last):
  File "./dorks.py", line 44, in <module>
    g_search(dorks_h1)
  File "./dorks.py", line 15, in g_search
    for report in search(query, stop=100):
  File "/home/balu/.local/lib/python3.6/site-packages/googlesearch/__init__.py", line 312, in search
    html = get_page(url, user_agent)
  File "/home/balu/.local/lib/python3.6/site-packages/googlesearch/__init__.py", line 176, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```
